data_filename: 'marketing_campaign.csv'

features:
  ID: int64
  Year_Birth: int64
  Education: object
  Marital_Status: object
  Income: float
  Kidhome: int64
  Teenhome: int64
  Dt_Customer: object
  Recency: int64
  MntWines: int64
  MntFruits: int64
  MntMeatProducts: int64
  MntFishProducts: int64
  MntSweetProducts: int64
  MntGoldProds: int64
  NumDealsPurchases: int64
  NumWebPurchases: int64
  NumCatalogPurchases: int64
  NumStorePurchases: int64
  NumWebVisitsMonth: int64
  AcceptedCmp3: int64
  AcceptedCmp4: int64
  AcceptedCmp5: int64
  AcceptedCmp1: int64
  AcceptedCmp2: int64
  Complain: int64
  Z_CostContact: int64
  Z_Revenue: int64
  Response: int64

label:
  Response: int64

continuous_features:
  - ID
  - Year_Birth
  - Income
  - Kidhome
  - Teenhome
  - Recency
  - MntWines
  - MntFruits
  - MntMeatProducts
  - MntFishProducts
  - MntSweetProducts
  - MntGoldProds
  - NumDealsPurchases
  - NumWebPurchases
  - NumCatalogPurchases
  - NumStorePurchases
  - NumWebVisitsMonth

discrete_features:
  - AcceptedCmp3
  - AcceptedCmp4
  - AcceptedCmp5
  - AcceptedCmp1
  - AcceptedCmp2
  - Complain
  - Z_CostContact
  - Z_Revenue
  
categorical_features:
  - Education
  - Marital_Status
  - Dt_Customer

domain_values:
  Education:
    - Graduation
    - PhD            
    - Master         
    - 2n Cycle       
    - Basic
  Marital_Status:
    - Married     
    - Together    
    - Single      
    - Divorced    
    - Widow       
    - Alone       
    - Absurd      
    - YOLO
  AcceptedCmp3:
    - 0
    - 1
  AcceptedCmp4:
    - 0
    - 1
  AcceptedCmp5:
    - 0
    - 1
  AcceptedCmp1:
    - 0
    - 1
  AcceptedCmp2:
    - 0
    - 1
  Complain:
    - 0
    - 1
  Z_CostContact:
    - 3
  Z_Revenue:
    - 11
  Response:
    - 0
    - 1

